all: mycp nl pessoas pessoas_opt

pessoas: pessoas.o

pessoas_opt: pessoas_opt.o

pessoa_opt.o: pessoas_opt.c

pessoas.o: pessoas.c

mycp: mycp.o

nl: readln.o nl.o

mycp.o: mycp.c

readln.o: readln.c readln.h

nl.o: nl.c readln.h
